const APP_MAIN_SCREEN_TITLE="Discover";
const SHOW_CASES_TITLE = "SHOWCASES";
const SHOW_CASES_SEE_MORE= "MORE SHOWCASES";
const BEST_ACTOR_TITLE="BEST ACTORS";
const BEST_ACTOR_SEE_MORE="MORE ACTORS";
const CHECK_MOVIES_SHOW_TIMES= "CHECK MOVIES\nSHOWTIMES";
const SEE_MORE="SEE_MORE";