///Hive Types
const int HIVE_TYPE_ID_ACTOR_VO= 1;
const int HIVE_TYPE_ID_COLLECTION_VO= 2;
const int HIVE_TYPE_ID_DATE_VO= 3;
const int HIVE_TYPE_ID_GENRE_VO= 4;
const int HIVE_TYPE_ID_MOVIE_VO= 5;
const int HIVE_TYPE_ID_PRODUCTION_COMPANIES_VO= 6;
const int HIVE_TYPE_ID_PRODUCTION_COUNTRIES_VO= 7;
const int HIVE_TYPE_ID_SPOKEN_LANGUAGES_VO= 8;

///Box names
const String BOX_NAMES_ACTOR_VO ="BOX_NAMES_ACTOR_VO";
const String BOX_NAMES_GENRE_VO ="BOX_NAMES_GENRE_VO";
const String BOX_NAMES_MOVIE_VO ="BOX_NAMES_MOVIE_VO";